name:                yael-opentracing
version:             0.1.0.0

_include: !include '../package.yaml'

extra-source-files:
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/benweitzman/yael-opentracing#readme>

<<: *common

dependencies:
- base >= 4.7 && < 5
- yael
- text
- opentracing
- safe-exceptions
- transformers

default-extensions:
  *default-extensions

library:
  source-dirs: src

executables:
  yael-opentracing-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yael-opentracing

tests:
  yael-opentracing-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yael-opentracing
