name:                yael-http-opentracing
version:             0.1.0.0

_include: !include '../package.yaml'

extra-source-files:
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/benweitzman/yael#readme>

<<: *common

dependencies:
- base >= 4.7 && < 5
- yael
- yael-opentracing
- yael-http
- opentracing
- http-client
- http-types
- network-uri
- lens
- transformers
- text

default-extensions:
  *default-extensions

library:
  source-dirs: src

tests:
  yael-http-opentracing-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yael-http-opentracing
