name:                yael-postgres-opentracing
version:             0.1.0.0

_include: !include '../package.yaml'

extra-source-files:
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/githubuser/yael#readme>

<<: *common

dependencies:
- base >= 4.7 && < 5
- yael
- yael-opentracing
- yael-postgres
- text
- persistent
- mtl
- transformers
- opentracing
- lens
- postgresql-simple

default-extensions:
  *default-extensions

library:
  source-dirs: src

tests:
  yael-postgres-opentracing-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yael-postgres-opentracing
