name:                yael-http
version:             0.1.0.0

_include: !include '../package.yaml'

extra-source-files:
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/benweitzman/yael#readme>

<<: *common

dependencies:
- base >= 4.7 && < 5
- http-client
- http-types
- bytestring
- yael
- monad-control
- transformers-base
- containers

default-extensions:
  *default-extensions

library:
  source-dirs: src

executables:
  yael-http-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yael-http

tests:
  yael-http-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yael-http
